language: swift
osx_image: xcode10
xcode_project: Piuma.xcodeproj
matrix:
    include:
    -   name: PiumaCore-iOS
        script: set -o pipefail && xcodebuild -project Piuma.xcodeproj -scheme PiumaCore-iOS -destination 'platform=iOS Simulator,OS=12.0,name=iPhone X' build test | xcpretty
    -   name: PiumaCore-macOS
        script: set -o pipefail && xcodebuild -project Piuma.xcodeproj -scheme PiumaCore-macOS -destination 'platform=macOS' build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
